FROM node:20

# Setting the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json files to the working directory
COPY package*.json ./

# Install the application dependencies
RUN npm install

# Copy the rest of the application code to the working directory
COPY . .

# Build the application (if you have a build step, for example with React)
RUN npm run build

# Expose the port on which the app will run
EXPOSE 5000

# Command to run the application
CMD ["node", "server.js"]
